name: Run Katalon Test Suite (KRE Execution)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  katalon-test:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Katalon Runtime Engine
        run: |
          Invoke-WebRequest -Uri https://github.com/katalon-studio/katalon-studio/releases/download/v9.1.0/Katalon_Studio_Engine_Windows_64-9.1.0.zip -OutFile katalon.zip
          Expand-Archive katalon.zip -DestinationPath katalon

      - name: Run Katalon Test Suite
        env:
          KATALON_API_KEY: ${{ secrets.KATALON_API_KEY }}
        run: |
          ./katalon/Katalon_Studio_Engine_Windows_64-9.1.0/katalonc.exe ^
            -noSplash ^
            -runMode=console ^
            -projectPath="$(Get-Location)\Record and Replay.prj" ^
            -retry=0 ^
            -testSuitePath="Test Suites/Smoke Testing" ^
            -executionProfile="default" ^
            -browserType="Chrome (headless)" ^
            -apiKey=$env:KATALON_API_KEY

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: Katalon-Test-Reports
          path: Reports/
