name: Run Katalon Test Suite (Linux)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  katalon-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Katalon Runtime Engine (Linux)
        run: |
          wget https://github.com/katalon-studio/katalon-studio/releases/download/v9.1.0/Katalon_Studio_Engine_Linux_64-9.1.0.tar.gz -O katalon.tar.gz
          tar -xzf katalon.tar.gz -C katalon

      - name: Run Katalon Test Suite
        env:
          KATALON_API_KEY: ${{ secrets.KATALON_API_KEY }}
        run: |
          ./katalon/katalonc -noSplash -runMode=console -projectPath="$(pwd)/Record and Replay.prj" -retry=0 -testSuitePath="Test Suites/Smoke Testing" -executionProfile="default" -browserType="Chrome (headless)" -apiKey=$KATALON_API_KEY

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: Katalon-Test-Reports
          path: Reports/
